### ISSUE TITLE
Oblivion Smashed Patch: causing Wrye bash to not open, unable to open in xEdit

### ISSUE THREAD

**Issue by Sabre142** [matortheeternal/smash#178]
Used the quick patch button. The smashed patch being in my data directory will cause Wrye Bash to not open. Dragging it into my data folder after Wrye is open gives this error. Cannot open the smashed patch in TES4Edit without it receiving an error.

'WARNING -> RecordProcessor: Information lost. Record skipped due to duplicate FORMID. [MOD=(Smashed Patch.esp), MODID=(23), FORMID=(00000000) TYPE=(    )]
Traceback (most recent call last):
  File "bash\balt.pyo", line 1605, in _conversation_wrapper
  File "bash\basher\__init__.pyo", line 3754, in RefreshData
  File "bash\bosh\__init__.pyo", line 2002, in refresh
  File "bash\bosh\__init__.pyo", line 2110, in rescanMergeable
  File "bash\bosh\__init__.pyo", line 2130, in _rescanMergeable
  File "bash\bosh\_mergeability.pyo", line 187, in isCBashMergeable
  File "bash\bosh\_mergeability.pyo", line 127, in _modIsMergeableLoad
  File "bash\cint.pyo", line 15432, in load
WindowsError: exception: access violation reading 0x0AC56000`

**Comment by Sabre142** [comment]
Wrye error: https://pastebin.com/raw/hNuiQJTW

Smash log (7mb): http://www.mediafire.com/file/cah8129af9hdd5w/log_051118_170051.txt

I think it is just a certain esp (unsure of which) that smash is not getting along with.

Building a smashed patch with only about 10 mods gives me this when I check smashed patch for errors in xEdit: ![capture](https://user-images.githubusercontent.com/26516348/39912455-1f01efdc-5542-11e8-9e01-207e4435d362.PNG)

**Comment by matortheeternal** [comment]
Looks like there may be some null formIDs in the smashed patch?  :thinking:

I highly recommend just using the bashed patch for Oblivion for the time being.
